### ISSUE TITLE
Please provide more information

### ISSUE THREAD

**Issue by N4M3Z** [ascii-soup/zsh-url-highlighter#1]
I am having trouble getting the zsh-url-highlighter working on zsh 5.0.7 (x86_64-apple-darwin14.0.0), could you provide a simple use-case example in your readme? I am doing this to load the functions:

```
source "ascii-soup/zsh-url-highlighter-master/url/url-highlighter.zsh"
fpath=(ascii-soup/zsh-url-highlighter-master/url)
```

**Comment by ascii-soup** [comment]
Hi - apologies for the scant docs, this was just a quick bit of code I wrote whilst trying to learn zsh. I'll give you a hand getting it running, with the caveat that it probably won't work even if you do!

First things first then, do you have the zsh syntax highlighting plugin installed? You can find it here if not: https://github.com/zsh-users/zsh-syntax-highlighting

**Comment by N4M3Z** [comment]
Yes, I have it installed. So now your plugin should turn the URL i type into the console green/red depending on whether it is correct, right?

Also, upon investigating your plugin, I realised, that the URL has to be preceeded with http:// not https://. This is perhaps something that I could help improving once I get the thing working )

**Comment by ascii-soup** [comment]
Sorry for the long delay, I have had little time lately.

Just to confirm, as it appears to work for me, does your .zshrc have something like this in it?

``` sh
source ~/.zsh/zsh-url-highlighter/url/url-highlighter.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets url)
```

**Comment by N4M3Z** [comment]
I see, it never occurred to me to add it into into the zsh highlighters ... once I did this it all seems to work correctly. I am going to update the README file and send a pull request. I would also like to add https, how would you suggest to do that? I see that you pass it as an argument here:

```
_zsh_highlight_url_highlighter_loop "$BUFFER" "(http://[^\n'\"]*)"
```

So either we simply add another argument to `_zsh_highlight_url_highlighter_loop` or adjust the reqexp `(http://[^\n'\"]*)` somehow?

**Comment by ascii-soup** [comment]
Adjusting the regex is probably the easiest/clearest option, I think. Thanks for the interest :)

**Comment by ascii-soup** [comment]
Closing - have updated the README to reflect better installation instructions etc.
