### ISSUE TITLE
URLs no longer highlighted unless they are the beginning of the line

### ISSUE THREAD

**Issue by ascii-soup** [ascii-soup/zsh-url-highlighter#3]
Just need to remove the ^ from the regex, I think.

**Comment by pkill37** [comment]
Has this been fixed? Is this still working at all? I'd love to install it if so :)

**Comment by ascii-soup** [comment]
I'm not sure, I doubt it - the regex needs a little tweak but I won't have
the opportunity to fix until Monday I'm afraid.

Be aware that it's quite rough, although I'm very tempted to pick this back
up and improve it.

If you remember, bump me on Monday :)

**Comment by ascii-soup** [comment]
OK I've checked and this is still causing me an issue (with a fresh clone) on linux (not sure about mac, don't use one) - I've had a bunch of useful comments about the code here in #4 (and apparently people are using this!) so I've some more incentive to try and fix this up and turn it into a proper package that works.

Watch this space!

**Comment by ascii-soup** [comment]
I've gone #4 and just rewritten it all from scratch, so this should no longer be an issue.
