### ISSUE TITLE
Code review: warnings and server flooding

### ISSUE THREAD

**Issue by danielshahaf** [ascii-soup/zsh-url-highlighter#4]
Hello!  z-sy-h upstream maintainer here.  I just ran across this repository, and have a few comments on the [current](https://github.com/ascii-soup/zsh-url-highlighter/blob/8977f6ded9a2038e241458e011aff1afad340639/url/url-highlighter.zsh#L21) code:
1. Warnings under z-sy-h HEAD (due to warncreateglobal):
   
   ```
   _zsh_highlight_url_highlighter_loop:5: scalar parameter MATCH created globally in function _zsh_highlight_url_highlighter_loop
   _zsh_highlight_url_highlighter_loop:5: numeric parameter MBEGIN created globally in function _zsh_highlight_url_highlighter_loop
   _zsh_highlight_url_highlighter_loop:5: numeric parameter MEND created globally in function _zsh_highlight_url_highlighter_loop
   ```
2. Running curl _after every keystroke_ could flood a server with requests.  I suggest you consider caching the results, if not outright waiting for the user to stop typing before pinging the URL.
3. The recursive calls seem redundant; using `functions -T` to get a trace gives:
   
   ```
   +_zsh_highlight_url_highlighter_loop:3> local buf='https://www.example.com/ ' pat='(^https?://[^\n'\''"]*) '
   +_zsh_highlight_url_highlighter_loop:4> local -a match mbegin mend
   +_zsh_highlight_url_highlighter_loop:5> [[ "$buf" -regex-match "${pat}" ]]
   +_zsh_highlight_url_highlighter_loop:6> curl -sIL -m 4 -w '' https://www.example.com/ -o /dev/null
   +_zsh_highlight_url_highlighter_loop:7> local exitCode=0
   +_zsh_highlight_url_highlighter_loop:8> [[ 0 -eq 0 ]]
   +_zsh_highlight_url_highlighter_loop:9> region_highlight+=( '0 24 fg=green' ) 
   +_zsh_highlight_url_highlighter_loop:10> _zsh_highlight_url_highlighter_loop https://www.example.com/ '(^https?://[^\n'\''"]*) '
   +_zsh_highlight_url_highlighter_loop:3> local buf=https://www.example.com/ pat='(^https?://[^\n'\''"]*) '
   +_zsh_highlight_url_highlighter_loop:4> local -a match mbegin mend
   +_zsh_highlight_url_highlighter_loop:5> [[ "$buf" -regex-match "${pat}" ]]
   +_zsh_highlight_url_highlighter_loop:10> return 0
   ```
   
   As you can see, if $BUFFER consists of a URL followed by N spaces, then curl will be called N+1 times.  That's _per _zsh_highlight call_, so if you physically type in a URL followed by N spaces, curl will be invoked O(N²) times in total.

That's it.  I'm glad to see third-party highlighter plugins existing!

**Comment by ascii-soup** [comment]
Hi,

Thanks so much for the feedback, greatly appreciated.

This was pretty much just an exercise to see if I could get a custom highlighter to work; as far as I know, nobody uses it (including me!)

However, having said that, I'm interested in picking this back up and [making an attempt at] turning it into a viable highlighter and your feedback will be really helpful in doing so.

I know very little about zsh from a development POV, so would I be able to bug you for help with this? For example, I know very little about debugging functions and so on, and any help you could give me (even just to point at an article on the web) would be well received.

Thanks again!

**Comment by danielshahaf** [comment]
ASCII Soup wrote on Mon, Apr 04, 2016 at 03:45:31 -0700:

> This was pretty much just an exercise to see if I could get a custom
> highlighter to work; as far as I know, nobody uses it (including me!)

Hmm.  The repository is starred and forked, you get PRs, and you're mentioned on https://github.com/unixorn/awesome-zsh-plugins/... Perhaps you do have users, then ;-)

> However, having said that, I'm interested in picking this back up and [making an attempt at] turning it into a viable highlighter and your feedback will be really helpful in doing so.
> 
> I know very little about zsh from a development POV, so would I be able to bug you for help with this? For example, I know very little about debugging functions and so on, and any help you could give me (even just to point at an article on the web) would be well received.

There's `functions -T ${funcname}` and `functions -t ${funcname}` to enable tracing for a function or for a function and all its callees recursively, documented in the zsh manual [in zshbuiltins(1) if you're reading it in man page form].  You'd run these commands interactively, after the function had been defined, and then trace info will be emitted whenever the function is called.

Also, look up `fned` in the zsh manual.

I'd be happy to help with z-sy-h-specific issues, of course, but for issues generic to zsh I think it would be best for me to direct you to the zsh-users@ mailing list and the #zsh IRC channel on freenode.  I do read both of these (I'm `danielsh` on IRC), but by asking there you'd be able to benefit from more people's knowledge, get answers more quickly, etc.

Moreover, merely lurking on these two places may teach you a lot about zsh; it's how I discovered many features.

(We also have a #zsh-syntax-highlighting channel, by the way.)

Cheers,

**Comment by ascii-soup** [comment]
> Perhaps you do have users, then ;-)

Evidently! Looks like I need to be a bit more responsible about it then! :-)

Thanks for the pointers, I've joined both IRC channels and will start wandering about in the docs.

Thanks again!

**Comment by ascii-soup** [comment]
Rewritten from scratch following the advice here and after talking to @danielshahaf on IRC. Thanks for your input and taking the time to help me with this :-)
